namespace Basic.Application.Threading;
class SharedResource
{
    public static int[] Data{get;set;}  //Store data values generated by the producer thread
    public static int BatchCount { get; set; } // Num of partition

    public static int BatchSize{get;set;} // Num of items in each partition

    //manualresetevent is used to signal the consumer thread when the producer has finished producing items
    public static ManualResetEvent ProducerFinished;

    public static AutoResetEvent ProducerFinishedAuto;
    static SharedResource()
    {
        Data=new int[15]; // Initialize the data array with a fixed size
        BatchCount=5; // Initialize the count to zero
        BatchSize=3; // Initialize the batch size to 3 items per batch
        ProducerFinished = new ManualResetEvent(false); // Initially, the producer has not finished
        ProducerFinishedAuto = new AutoResetEvent(false); // Initially, the producer has not finished
    }
}

class Producer
{
    public void Produce()
    {
        Console.WriteLine("Producer is starting to produce items...");
        for (int i = 0; i < SharedResource.Data.Length; i++)
        {
            SharedResource.Data[i] = i + 1; // Simulate producing data by filling the array with values
            Console.WriteLine($"Producer produced: {SharedResource.Data[i]}");
            Thread.Sleep(300); // Simulate time taken to produce an item
        }
            SharedResource.ProducerFinished.Set(); // Signal that the producer has finished producing items
            Console.WriteLine("Producer has finished producing items.");
    }

    public void ProduceWithManualReset()
    {
        Console.WriteLine("Producer is starting to produce items...");
        for (int batch = 0; batch < SharedResource.BatchCount; batch++)
        {
            //Console.WriteLine($"Producer is producing batch {batch + 1}...");
            for (int i = 0; i < SharedResource.BatchSize; i++)
            {
                int index = batch * SharedResource.BatchSize + i;
                if (index < SharedResource.Data.Length)
                {
                    SharedResource.Data[index] = index + 1; // Simulate producing data by filling the array with values
                    //Console.WriteLine($"Producer produced: {SharedResource.Data[index]}");
                    Thread.Sleep(300); // Simulate time taken to produce an item
                }
            }
            SharedResource.ProducerFinished.Set(); // Signal that the producer has finished producing the current batch
           // Console.WriteLine($"Producer has finished producing batch {batch + 1}.");
            SharedResource.ProducerFinished.Reset(); // Reset the event for the next batch
        }
        Console.WriteLine("Producer has finished producing items.");
    }
    public void ProduceWithAutoReset()
    {
        Console.WriteLine("Producer is starting to produce items...");
        for (int batch = 0; batch < SharedResource.BatchCount; batch++)
        {
            //Console.WriteLine($"Producer is producing batch {batch + 1}...");
            for (int i = 0; i < SharedResource.BatchSize; i++)
            {
                int index = batch * SharedResource.BatchSize + i;
                if (index < SharedResource.Data.Length)
                {
                    SharedResource.Data[index] = index + 1; // Simulate producing data by filling the array with values
                    //Console.WriteLine($"Producer produced: {SharedResource.Data[index]}");
                    Thread.Sleep(300); // Simulate time taken to produce an item
                }
            }
            SharedResource.ProducerFinishedAuto.Set(); // Signal that the producer has finished producing the current batch
           // Console.WriteLine($"Producer has finished producing batch {batch + 1}.");
            //SharedResource.ProducerFinished.Reset(); // Reset the event for the next batch
        }
        Console.WriteLine("Producer has finished producing items.");
    }

}

class Consumer
{
    public void Consume()
    {
        Console.WriteLine("Consumer is starting to consume items...Consumer will wait until the producer has finished producing items.");
        SharedResource.ProducerFinished.WaitOne(); // Wait for the producer to signal that it has finished producing items
        Console.WriteLine("Producer has finished. Consumer is now consuming items...");
        
        for (int i = 0; i < SharedResource.Data.Length; i++)
        {
            int item = SharedResource.Data[i]; // Simulate consuming data by reading values from the array
            Console.WriteLine($"Consumer consumed: {item}");
            Thread.Sleep(150); // Simulate time taken to consume an item
        }
        Console.WriteLine("Consumer has finished consuming items.");  
    }
    public void ConsumeWithManualReset()

    {
        Console.WriteLine("Consumer is starting to consume items...Consumer will wait until the producer has finished producing each batch.");
        for (int batch = 0; batch < SharedResource.BatchCount; batch++)
        {
            SharedResource.ProducerFinished.WaitOne(); // Wait for the producer to signal that it has finished producing the current batch
            Console.WriteLine($"Producer has finished batch {batch + 1}. Consumer is now consuming items from this batch...");
            
            for (int i = 0; i < SharedResource.BatchSize; i++)
            {
                int index = batch * SharedResource.BatchSize + i;
                if (index < SharedResource.Data.Length)
                {
                    int item = SharedResource.Data[index]; // Simulate consuming data by reading values from the array
                    Console.WriteLine($"Consumer consumed: {item}");
                    Thread.Sleep(150); // Simulate time taken to consume an item
                }
            }
            Console.WriteLine($"Consumer has finished consuming items from batch {batch + 1}.");
        }
        Console.WriteLine("Consumer has finished consuming all items.");  
    }

    public void ConsumeWithAutoReset()

    {
        Console.WriteLine("Consumer is starting to consume items...Consumer will wait until the producer has finished producing each batch.");
        for (int batch = 0; batch < SharedResource.BatchCount; batch++)
        {
            SharedResource.ProducerFinishedAuto.WaitOne(); // Wait for the producer to signal that it has finished producing the current batch
            //Console.WriteLine($"Producer has finished batch {batch + 1}. Consumer is now consuming items from this batch...");
            
            for (int i = 0; i < SharedResource.BatchSize; i++)
            {
                int index = batch * SharedResource.BatchSize + i;
                if (index < SharedResource.Data.Length)
                {
                    int item = SharedResource.Data[index]; // Simulate consuming data by reading values from the array
                    Console.WriteLine($"Consumer consumed: {item}");
                    Thread.Sleep(150); // Simulate time taken to consume an item
                }
            }
            Console.WriteLine($"Consumer has finished consuming items from batch {batch + 1}.");
        }
        Console.WriteLine("Consumer has finished consuming all items.");  
    }


}